---
title: "Archive - pre-2019 news"
date: '2019-01-01'
---

* May 2018: Nick, Steve, and Charles' paper on tunable spectral ordering of magnetic plasmon resonances in noble metal nanoclusters was accepted in  [ACS Photonics](https://pubs.acs.org/doi/10.1021/acsphotonics.8b00519) ! Congratulations All!!

* May 2018: Harrison, Kevin, and Jake's paper on mislocalization in plasmon-enhanced super-resolution fluorescence microscopy was accepted in  [ACS Photonics](https://pubs.acs.org/doi/10.1021/acsphotonics.8b00372) ! Congratulations!!

* March 2018: David and Stephan Link's thematic issue on  [Plasmonics in Chemistry](https://pubs.acs.org/toc/chreay/118/6)  was published online in Chemical Reviews!

* February 2018: Niket's work on plasmonic Landau damping in active environments in published in PRB as a Rapid Communication. Congrats Niket, Nick, and Charles!

* January 2018: Collaborative work with Prof. Jon Camden's group at Notre Dame on nanocube plasmon mode mixing in finite substrates is accepted for publication at JPC Letters!

* Fall 2017: Collaborative work with Prof. Randy Goldsmith's group at UW Madison on controlling photonic-plasmonic hybridization in optical microresonator cavities via thermal annealing is accepted for publication in Nano Letters. Congratulations All!

* Fall 2017: Collaborative work with Prof. Naomi Ginsberg's group at UC Berkeley on non-invasive cathodoluminescence imaging is accepted for publication in ACS Nano!

* Spring 2017: The Masiello group receives several grants from NSF CTMC, NSF EPM, NSF DMREF, and DOE BES. Congratulations! And, thank you NSF and DOE!

* April 2017: Niket Thakkar receives the prestigious  [UW Graduate Medal](http://grad.uw.edu/student-alumni-profiles/niket-thakkar/)  awarded each year to a single UW Ph.D., DMA, Au.D., DNP, DPT, or Ed.D. candidate who displays an exemplary commitment to both the University and its larger community. Congratulations Niket!

* April 2017: Kevin Smith receives an Outstanding First-Year TA Award from the UW Physics Department. Congratulations Kevin!

* March 2017: Niket Thakkar successfully defends his Ph.D. dissertation in Applied Mathematics and joins the Institute for Disease Modeling as a machine learning research scientist. Congratulations Niket!

* March 2017: Nick Montoni receives a  [Husky 100 Award!](http://www.washington.edu/husky100/blog/2017-husky-100/)  Congratulations Nick!!

* January 2017: Zhaoxia's paper on  [dynamic optical switching of polymer/plasmonic nanoparticle hybrids](http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.7b00013)  is accepted for publication in Journal of Physical Chemistry B

* November 2016: Niket, Steven, and Charles' paper on  [single-particle absorption spectroscopy via photothermal contrast in an optical microresonator cavity](http://www.nature.com/nphoton/journal/vaop/ncurrent/full/nphoton.2016.217.html)  is published online in Nature Photonics!
Press:  [C&E News](http://cen.acs.org/articles/94/i45/Whispering-microresonators-detect-absorption-spectra.html) ,  [Nature Photonics](http://www.nature.com/nphoton/journal/v10/n12/full/nphoton.2016.237.html) 

* September 2016: We're batting 3/3...Our collaborative work with the Camden group (Notre Dame) and Rack group (Tennessee) on  [magnetic plasmon hybridization and all-magnetic Fano interference](http://pubs.acs.org/doi/abs/10.1021/acs.nanolett.6b03504)  is accepted for publication in Nano Letters!

* September 2016: Niket, Steven, and Charles' collaborative paper with the Goldsmith group at UW, Madison on single-particle absorption spectroscopy via photothermal contrast in an optical microresonator cavity is accepted for publication in Nature Photonics

* September 2016: Nick Montoni's paper on  [imaging energy transfer between noble-metal and catalytic-metal nanoparticles with STEM/EELS](http://pubs.acs.org/doi/abs/10.1021/acs.jpclett.6b01878)  is accepted for publication in JPC Letters

* April 2016: Steven, Charles, and Nick's paper on  [imaging plasmon hybridization in metal nanoparticle aggregates with STEM/EELS](http://pubs.acs.org/doi/abs/10.1021/acs.jpcc.6b02170)  is accepted for publication in JPC C!

* February 2016: David Masiello receives a Presidential Early Career Award for Scientists and Engineers (PECASE).
Press:  [White House](https://www.whitehouse.gov/the-press-office/2016/02/18/president-obama-honors-extraordinary-early-career-scientists) ,  [NSF](http://www.nsf.gov/news/news_summ.jsp?cntn_id=137709&WT.mc_id=USNSF_1) ,  [UW](http://www.washington.edu/news/2016/02/18/three-uw-professors-win-presidential-early-career-award-for-scientists-and-engineers/) 

* February 2016: David Masiello is promoted to Associate Professor with tenure, effective Autumn Quarter 2016

* December 2015: Charles, Nick, and Nikets' paper on  [mapping the evolution from gold to silver LSPRs in alloyed nanoparticles via STEM/EELS](http://pubs.acs.org/doi/abs/10.1021/acsphotonics.5b00548)  is accepted for publication in ACS Photonics

* August/September 2015: David Masiello is invited to speak at the University of Pittsburgh and Notre Dame

* June 2015: Charles and Nick’s paper on  [mapping the transition from LSPRs to SPPs in truncated nanospheres via STEM/EELS](http://pubs.acs.org/doi/abs/10.1021/acs.jpclett.5b00961)  is accepted for publication in JPC Letters

* June 2015: UCSB physics major Claire West joins the group as a summer NSF REU student.  Welcome Claire!

* April 2015: Charles and Nick's paper on the  [spatial mapping of energy transfer in nanocubes via STEM/EELS](http://pubs.acs.org/doi/abs/10.1021/acs.nanolett.5b00802)  is accepted for publication in Nano Letters!

* April 2015: David Masiello gives an invited talk at the University of Pennsylvania

* March 2015: The Masiello group is heading to ACS Denver where Charles, Nick, and Niket will all be speaking in our PHYS Division Symposium on  [Probing Nano-Plasmonic Phenomena at the Single Molecule, Single Electron, & Single Photon Level](http://phys-acs.org/symposia/S2015.html) 

* January/February 2015: David Masiello gives invited talks at Stanford, UC Davis, Northwestern, and the University of Chicago

* December 2014: Niket and Charles publish their paper on  [quantum beats produced by entangled localized surface plasmons in metal nanoparticle aggregates](http://pubs.acs.org/doi/abs/10.1021/ph500387c)  in ACS Photonics!

* December 2014: Nicholas Bigelow successfully defends his Ph.D. dissertation on electron energy-loss spectroscopy theory and simulation in nanoparticle plasmonics.  Well done Dr. Bigelow!  Congratulations!! 

* December 2014: First year graduate student Nicholas Montoni from UNC Chapel Hill joins the group.  Welcome Nick!

* December 2014: Undergraduate researcher Jeremy Li receives a Mary Gates Research Scholarship to fund his proposed research in nanoscale temperature manipulation via Fano interferometry!

* November 2014: David Masiello is invited to speak at the University of Florida and at CREOL/University of Central Florida 

* September 2014: Charles Cherqui, Nicholas Bigelow, Alex Vaschillo, and Harrison Goldwyn publish our group’s first paper in ACS Photonics.  The paper provides  [a first-principles taxonomy of the electric and magnetic plasmon resonances of cyclic metal oligomer metamaterials](http://pubs.acs.org/doi/abs/10.1021/ph5002268) .

* September 2014: David Masiello is invited to speak at Rice University and the University of Texas at Austin later this month


* July 2014: Baby  [Cara Masiello](http://faculty.washington.edu/masiello/cara.jpg)  is born and is getting lots of love from her big brother Peter!


* June 2014: Senior undergraduate researcher Alex Vaschillo receives an NSF graduate research fellowship for his proposal on the electron energy-loss spectroscopy of plasmonic nanomaterials.  

Alex is the fourth Masiello group student since we began in Fall 2010 to be awarded the NSF graduate research fellowship in plasmonics theory!  Congratulations, Alex!!


* April 2014: Collaborative research with the Camden group at the University of Tennessee on the  [STEM/EELS-based Fano interferometry of the nanocube plasmon](http://pubs.acs.org/doi/abs/10.1021/jp412778y)  is accepted for publication in JPC C

* April 2014: Physics graduate student Chris Baldwin is awarded the prestigious NSF graduate research fellowship for his proposal on the theory of plasmon decay.    

* April 2014: Senior undergraduate researcher Alex Vaschillo receives an Honorable Mention for his NSF graduate research fellowship proposal.  Congrats Alex!

* March 2014: Chris Baldwin publishes his first paper entitled " [Thermal Signatures of Plasmonic Fano Interferences: Toward the Achievement of Nanolocalized Temperature Manipulation](http://pubs.acs.org/doi/abs/10.1021/jz500421z) " in the Journal of Physical Chemistry Letters. Congratulations, Chris!

* March 2014: David Masiello receives an adjunct faculty appointment in Physics at UW

* February 2014: David Masiello receives an adjunct faculty appointment in Applied Mathematics at UW

* January 2014: David Masiello gives an invited talk on Spectro-Nanoscopy at the  [Pacific Spectroscopy Conference](http://www.westernspectroscopy.org/Compiled%20Document.pdf)  in Asilomar, CA

* December 2013: Collaborative research with Prof. Gamelin's group on  [surface-plasmon resonances in charge-tunable semiconducting quantum dots](http://pubs.acs.org/doi/abs/10.1021/nn406126u)  is accepted for publication in ACS Nano

* December 2013: Chemistry graduate student Steven Quillin joins the group.  Welcome Steve!

* November 2013: Dr. Charles Cherqui from UNM Physics/LANL CNLS joins the group as a Postdoctoral Fellow.  Welcome Charles!

* November 2013: Nicholas Bigelow receives a S. P. Pavlou and D. E. Strayer Endowed Fellowship in Chemistry.  Way to go, Nick!

* October 2013: David Masiello is invited to speak at the First International Workshop on  [Electron Beam Spectroscopy for Nanophotonics](http://www.amolf.nl/ebsn/ebsn-home/)  at the FOM Institute, AMOLF in Amsterdam, The Netherlands in June 2014

* October 2013: Alex Vaschillo wins a prestigious fellowship from the Washington Research Foundation.  Congrats Alex!

* September 2013: David Masiello gives an invited talk at LANL’s CNLS

* August 2013: David Masiello is invited to UC Irvine and University of Victoria for pchem seminars

* July 2013: Physics graduate student Christopher Baldwin joins the group.  Welcome Chris!

* June 2013: Harrison Goldwyn, a UCSB physics major, joins the group as a summer NSF REU student.  Welcome!

* June 2013: Alex Vaschillo receives a Mortar Board Alumni/Tolo Foundation Arnold & Carolyn Bryant Peterson Scholarship.  Congratulations Alex!!

* May 2013: David Masiello is invited to speak at the  [61st Pacific Conference on Spectroscopy and Dynamics](http://www.westernspectroscopy.org/)  in Asilomar, CA in January 2014

* May 2013: Undergraduate researcher Alex Vaschillo is named an Astronaut Scholarship Foundation Fellow and is awarded a $10 K scholarship. Also Alex has received a NSF-funded REU position at Harvard University during Summer 2013. Congratulations Alex!

* May 2013: Jonathan, Ryan, and Bo’s paper on the quantum image effect is accepted for publication in the  [Journal of Physical Chemistry C](http://pubs.acs.org/doi/abs/10.1021/jp403047t) 

* April 2013: Nick and Alex’s paper on unraveling the signatures of Fano interferences in electron energy-loss spectroscopy (EELS) and cathodoluminescence (CL) is accepted in  [ACS Nano](http://dx.doi.org/10.1021/nn401161n) 

* April 2013: David Masiello receives an  [outstanding junior faculty award from the COMP Division of the ACS](http://web2011.acscomp.org/comp-news/theopeneyeoutstandingjuniorfacultyawardwinnersforindianapolisfall2013) 

* March 2013: Niket Thakkar wins an  [NSF Graduate Research Fellowship!](https://www.fastlane.nsf.gov/grfp/AwardeeList.do?method=loadAwardeeList)   Congratulations Niket!!

* March 2013: David Masiello is invited to speak at the 34th Progress in Electromagnetic Research Symposium in Stockholm, Sweden in August 2013

* January 2013: Alex Vaschillo receives a Rex. J. and Ruth C. Robinson Scholarship in Chemistry and is invited to present his EELS research at the National Collegiate Research Conference at Harvard University, Cambridge MA.  Congrats Alex!

* December 2012: Jonathan Litz receives a Leon J. Slutsky Endowed Fellowship in Chemistry

* October 2012: David Masiello is awarded a  [CAREER award from the National Science Foundation](http://www.nsf.gov/awardsearch/showAward?AWD_ID=1253775&HistoricalAwards=false) 

* October 2012: David Masiello is invited to speak at the  [43rd Winter Colloquium on the Physics of Quantum Electronics](http://www.pqeconference.com/pqe2013/index.shtml)  

* September 2012: We are freely distributing the electron-driven discrete dipole approximation (e-DDA) under the GNU General Public License

* August 2012: Collaborative research with the groups of Prof. Jon Camden at UTK, Prof. Beth Guiton at UK, and Dr. Stephen Pennycook at ORNL is accepted for publication in  [JPC Letters](http://pubs.acs.org/doi/abs/10.1021/jz300967q) 

* July 2012: Nick and Alex’s paper on using electron energy-loss spectroscopy (EELS) to probe SERS hot spots is accepted in  [ACS Nano](http://pubs.acs.org/doi/abs/10.1021/nn302980u) 

* June 2012: NNIN REU student, Bo Lee from Harvey Mudd College, joins the group this Summer.  Welcome Bo!

* April 2012: Applied Math graduate student Niket Thakkar joins the group

* April 2012: David Masiello is invited to be a plenary speaker at  [MMM 2012](http://www.mrs.org.sg/mmm2012/public.asp?page=home.asp)  in Singapore this October

* March 2012: Jonathan Litz has been invited to attend the  [2012 Lindau Nobel Laureate Meeting](http://www.lindau-nobel.org/2012_62nd_Lindau_Meeting.AxCMS)  in Lindau, Germany.  Congratulations, Jonathan!

* February 2012: David Masiello is invited to speak at the Multiscale Modeling, Analysis, and Computation of Nano-Optics Workshop at Michigan State University in East Lansing, MI in April 2012

* February 2012: Jonathan Litz has received a travel award from the UW Graduate School Fund for Excellence and Innovation (GSFEI) to attend the Spring 2012 ACS meeting in San Diego, CA.  Congrats Jonathan!

* February 2012: David Masiello has joined the faculty of the  [Center for Nanotechnology](http://www.nano.washington.edu/index.asp)  at the University of Washington

* February 2012: David Masiello is invited to speak at “Quantum Effects in Condensed-Phase Systems” at the Telluride Science Research Center in Telluride, CO in July 2013

* January 2012: UW undergrad, Alex Vaschillo joins the group.  Welcome Alex!

* January 2012: Collaborative research with the group of Prof. Katherine Willets at UT Austin is accepted for publication in  [ACS Nano](http://pubs.acs.org/doi/abs/10.1021/nn205080q) 

* January 2012: David Masiello is invited to speak at the University of Oregon, Department of Chemistry

* January 2012: Applied Math graduate student Tim Sooter joins the group.

* December 2011: David Masiello is invited to speak at “Nanomaterials: Theory and Computation” at the Telluride Science Research Center in Telluride, CO in July 2012

* December 2011: David Masiello is invited to speak at Chalmers University of Technology in Göteborg, Sweden in January 2012

* November 2011: David Masiello is invited to speak in “Multiscale Modeling of Optically Responsive Materials” at the October 2012 Multiscale Materials Modeling (MMM) conference in Singapore


* September 2011: The Masiello group welcomes its newest junior theorist -  [Peter William Masiello!](http://faculty.washington.edu/masiello/peter.jpg)  


* September 2011: David Masiello is invited to speak in “Theoretical Approaches in Molecular Spectroscopy” at the 95th Canadian Chemistry Conference in May 2012

* June 2011: David Masiello is invited to speak at UW’s Center for Nanotechnology 15th Anniversary Workshop in September 2011

* June 2011: Jonathan Litz publishes the group’s  [first paper in the Journal of Physical Chemistry Letters](http://pubs.acs.org/doi/abs/10.1021/jz200743t?prevSearch=%2528masiello%2529%2BNOT%2B%255Batype%253A%2Bad%255D%2BNOT%2B%255Batype%253A%2Bacs-toc%255D&searchHistoryKey=) 

* June 2011: UW undergrads Jeff Schueler and Brad Krajina join the group, and Harvey Mudd undergrad Ryan Brewster joins the group for the Summer.  Welcome all!

* June 2011: Steven Spackman receives dual B.S. degrees in Chemistry and Biochemistry from UW.  Congratulations Steven!

* April 2011: Congratulations to Jonathan Litz for receiving the  [NSF Graduate Research Fellowship](http://www.nsfgrfp.org/) !

* January 2011: Masiello group receives  [funding from the UW Royalty Research Fund](http://www.washington.edu/research/main.php?page=rrfAwardeeList&period=JAN2011) 

* December 2010: David Masiello is invited to speak in “Advances in SERS and Molecular Plasmonics“ at the Fall 2011 ACS meeting in Denver, CO

* November 2010: David Masiello is invited to speak in “Reduced Density Matrices in Quantum Chemistry and Physics” at the Fall 2011 ACS meeting in Denver, CO.

* November 2010: Chemistry grad students Nick Bigelow from UW and Ross Grimshaw from the University of Vermont join the group

* September 2010: UW undergrad Steven Spackman joins the group

* August 2010: Collaborative work between the Masiello group and the experimental groups of Professors David Ginger, Mehmet Sarikaya, and Alex Jen is  [published (and gets the inside front cover!) in Advanced Functional Materials](http://onlinelibrary.wiley.com/doi/10.1002/adfm.201090069/abstract)  

* July 2010: Chemistry grad student Jonathan Litz joins the group from Harvey Mudd College
